/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryDialogComponent: typeof import('./src/components/admin/category/CategoryDialogComponent.vue')['default']
    CategorySelect: typeof import('./src/components/admin/category/CategorySelect.vue')['default']
    DialogComponent: typeof import('./src/components/admin/DialogComponent.vue')['default']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IMaterialSymbolsAssistantNavigationOutlineRounded: typeof import('~icons/material-symbols/assistant-navigation-outline-rounded')['default']
    IMaterialSymbolsCategoryOutlineRounded: typeof import('~icons/material-symbols/category-outline-rounded')['default']
    IMaterialSymbolsDarkModeOutlineRounded: typeof import('~icons/material-symbols/dark-mode-outline-rounded')['default']
    IMaterialSymbolsHomeOutlineRounded: typeof import('~icons/material-symbols/home-outline-rounded')['default']
    IMaterialSymbolsSettings: typeof import('~icons/material-symbols/settings')['default']
    IMaterialSymbolsTagRounded: typeof import('~icons/material-symbols/tag-rounded')['default']
    IMaterialSymbolsUserAttributesOutlineRounded: typeof import('~icons/material-symbols/user-attributes-outline-rounded')['default']
    NavDialogComponent: typeof import('./src/components/admin/nav/NavDialogComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/user/SearchComponent.vue')['default']
    SettingsDialogComponent: typeof import('./src/components/admin/SettingsDialogComponent.vue')['default']
    TagDialogComponent: typeof import('./src/components/admin/tag/TagDialogComponent.vue')['default']
    TagSelect: typeof import('./src/components/admin/tag/TagSelect.vue')['default']
    TimeDateCard: typeof import('./src/components/user/TimeDateCard.vue')['default']
    TimeDateCardComponent: typeof import('./src/components/user/TimeDateCardComponent.vue')['default']
    UserDialogComponent: typeof import('./src/components/admin/user/UserDialogComponent.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
