/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryDialogComponent: typeof import('./src/components/category/CategoryDialogComponent.vue')['default']
    DarkComponent: typeof import('./src/components/DarkComponent.vue')['default']
    DialogComponent: typeof import('./src/components/DialogComponent.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IMaterialSymbolsAssistantNavigationOutlineRounded: typeof import('~icons/material-symbols/assistant-navigation-outline-rounded')['default']
    IMaterialSymbolsCategoryOutlineRounded: typeof import('~icons/material-symbols/category-outline-rounded')['default']
    IMaterialSymbolsHomeOutlineRounded: typeof import('~icons/material-symbols/home-outline-rounded')['default']
    IMaterialSymbolsTagRounded: typeof import('~icons/material-symbols/tag-rounded')['default']
    IMaterialSymbolsUserAttributesOutlineRounded: typeof import('~icons/material-symbols/user-attributes-outline-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagDialogComponent: typeof import('./src/components/tag/TagDialogComponent.vue')['default']
    TagSelect: typeof import('./src/components/tag/TagSelect.vue')['default']
    UserDialogComponent: typeof import('./src/components/user/UserDialogComponent.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
